# ===============================================
# = CONFIGURATION DU SERVER WEB EMBARQUE TOMCAT =
# ===============================================
# Spring Boot incluent par défaut un serveur Web intégré préconfiguré, adresse et port du serveur  8080 par défaut.
server:
  port: 9000

# ======================================
# = CONFIGURATION DE LA JOURNALISATION =
# ======================================
logging:
  level:
    # Permet de voir dans la console le port utilisé par Tomcat au démarrage
    org.springframework.boot.web.embedded.tomcat: INFO
    root: INFO
    com.example: DEBUG

# =============================
# = DEFINIR PLUSIEURS PROFILS =
# =============================
# https://www.baeldung.com/spring-profiles

# deux profils : "dev" et "prod". Le profil actif est défini sur "dev"
spring:
  profiles:
    # profil a charger par défaut defini dans application.yml
    # active: dev
    # Profil Maven : peut être activé via la propriété de configuration spring.profiles.active
    #	Sa valeur sera utilisée pour remplacer l' espace réservé @spring.profiles.active@ dans application.properties ou application.yml
    active: @spring.profiles.active@


---
spring:
  #  Définir des propriétés spécifiques pour chaque profil
  config:
    activate:
      on-profile: dev
  # ============================================
  # = CONFIGURATION DE LA BASE DE DONNEE MySQL =
  # ============================================
  datasource:
    url: jdbc:mysql://localhost:3306/auth_jwt
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop   # Hibernate va créer le schéma de base de données à partir des entités annotées. À la fin de l'application, le schéma sera supprimé.
      # ddl-auto: create        # Hibernate va créer le schéma de base de données à partir des entités annotées. Si des tables existent déjà, elles seront supprimées et recréées.
      # ddl-auto: none:         # Aucune action DDL automatique ne sera effectuée par Hibernate. Cela signifie que vous devez gérer manuellement la création et la mise à jour des schémas de base de données.
      # ddl-auto: update        # Hibernate va mettre à jour le schéma de base de données pour refléter les changements apportés aux entités annotées. Cela peut inclure la création de nouvelles tables, l'ajout de nouvelles colonnes, etc. Les données existantes ne seront pas supprimées.
      # ddl-auto: validate      # Hibernate va valider le schéma de base de données par rapport aux entités annotées, mais aucune modification ne sera apportée à la base de données.


    # Le moyen le plus simple de vider les requêtes sql vers la sortie standard mais a priori non recommandé
    show-sql: true
    properties:
      hibernate:
        # Pour embellir
        format_sql: true
        #database: mysql
        #database-plateform:
      javax:
        persistence:
          schema-generation:
            scripts:
              # Génère un schéma de BDD avec Spring Boot JPA à partir des des entités
              # Actions ( https://www.baeldung.com/spring-data-jpa-generate-db-schema)
              #       none            - ne génère aucune commande DDL
              #       create          - génère uniquement des commandes de création de base de données
              #       drop            - génère uniquement des commandes de suppression de base de données
              #       drop-and-create - génère des commandes de suppression de base de données suivies de commandes de création
              # action: create
              # create-target: create.sql
              # create-source: metadata

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/proddatabase
    username: produser
    password: prodpassword



